context:
  # note v1.9.0 tag is the same as v0.1.9, except for CI changes,
  # and it installs as torchsort-0.1.9
  version: 0.1.9
  build_number: 0
  torch_proc_type: ${{ "cuda" ~ cuda_compiler_version | version_to_buildstring if cuda_compiler_version != "None" else "cpu" }}

package:
  name: torchsort
  version: ${{ version }}

source:
  - url: https://github.com/teddykoker/torchsort/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 343e60596cbe6a3397b04f91299243e8583810cbb8bbc016af0f0f2c75124dde
  # needed for tests
  - url: https://github.com/google-research/fast-soft-sort/archive/6a52ce79869ab16e1e0f39149a84f50f8ad648c5.tar.gz
    sha256: 6609ce8a167c95be86d11871a1591dd6cb097e0c41a7ca522ffb76199443daa7
    file_name: fast-soft-sort.tar.gz

build:
  number: ${{ build_number }}
  string: ${{ torch_proc_type }}_py${{ python | version_to_buildstring }}_h${{ hash }}_${{ build_number }}
  # CUDA < 12 not supported by pytorch anymore
  skip: cuda_compiler_version == "11.8"

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: cuda_compiler_version != "None"
      then:
        - ${{ compiler('cuda') }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pytorch * [build=${{ torch_proc_type }}*]
  host:
    - pip
    - python
    - setuptools
    - if: cuda_compiler_version != "None"
      then:
        - cuda-version ==${{ cuda_compiler_version }}
    - pytorch * [build=${{ torch_proc_type }}*]
  run:
    - python
    - pytorch * [build=${{ torch_proc_type }}*]

tests:
  - python:
      imports:
        - torchsort
        - torchsort.isotonic_cpu
        - if: cuda_compiler_version != "None"
          then:
            - torchsort.isotonic_cuda
      pip_check: true
  - files:
      source:
        - fast-soft-sort.tar.gz
        - tests/**
    requirements:
      run:
        - numba
        - numpy
        - pip
        - pytest
        - scipy
    script:
      - pip install ./fast-soft-sort.tar.gz
      - pytest tests

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Fast, differentiable sorting and ranking in PyTorch
  homepage: https://github.com/teddykoker/torchsort
  repository: https://github.com/teddykoker/torchsort

extra:
  recipe-maintainers:
    - mgorny
  feedstock-name: torchsort
